import "./globals.css";
import DarkModeProvider from "@/darkModeContext/DarkMode";
import { Manrope } from "next/font/google";

const manrope = Manrope({ subsets: ["latin"], weight: ["400", "600", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${manrope.className} antialiased`}>
        <DarkModeProvider>{children}</DarkModeProvider>
      </body>
    </html>
  );
}
