import { Inter } from "next/font/google";
import "./globals.css";
import { AuroraBackground } from "@/components/ui/aurora-background";
import DarkModeProvider from "@/darkModeContext/DarkMode";

const inter = Inter();

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <AuroraBackground>
          <DarkModeProvider>{children}</DarkModeProvider>
        </AuroraBackground>
      </body>
    </html>
  );
}
